[general]
enabled = yes
pretty = yes
; ARI hodisalari uchun WebSocket: ws://asterisk:8088/ari/events
allowed_origins = *

[aicc]
type = user
read_only = no
password = aicc_ari_password
password_format = plain
